package ai.chat2db.spi.constant;

public final class SQLConstants {

    public static final String EMPTY = "";
    public static final String SPACE = " ";
    public static final String TAB = "\t";
    public static final String DOT = ".";
    public static final String COLON = ":";
    public static final String AT = "@";
    public static final String COMMA = ",";
    public static final String COMMA_SPACE = ", ";
    public static final char COMMA_CHAR = ',';
    public static final String SEMICOLON = ";";
    public static final String LINE_SEPARATOR = "\n";
    public static final String DOUBLE_LINE_SEPARATOR = "\n\n";
    public static final String COMMA_LINE_SEPARATOR = ",\n";
    public static final String SEMICOLON_LINE_SEPARATOR = ";\n";
    public static final String SINGLE_QUOTE = "'";
    public static final String DOUBLE_QUOTE = "\"";
    public static final String BACK_QUOTE = "`";
    public static final String BACKSLASH = "\\";
    public static final String OPEN_PARENTHESIS = "(";
    public static final String CLOSE_PARENTHESIS = ")";
    public static final String OPEN_CURLY_BRACE = "{";
    public static final String CLOSE_CURLY_BRACE = "}";
    public static final String OPEN_SQUARE_BRACKET = "[";
    public static final String CLOSE_SQUARE_BRACKET = "]";
    public static final String SPACE_OPEN_PARENTHESIS = " (";
    public static final String CLOSE_PARENTHESIS_SPACE = ") ";
    public static final String LINE_SEPARATOR_CLOSE_PARENTHESIS = "\n)";
    public static final String LINE_SEPARATOR_CLOSE_PARENTHESIS_SEMICOLON = "\n);";
    public static final String CLOSE_PARENTHESIS_SEMICOLON_LINE_SEPARATOR = ");\n";
    public static final String SINGLE_QUOTE_SEMICOLON = "';";
    public static final String SINGLE_QUOTE_SEMICOLON_LINE_SEPARATOR = "';\n";
    public static final String DOUBLE_QUOTE_SEMICOLON = "\";";
    public static final String DOUBLE_QUOTE_SEMICOLON_LINE_SEPARATOR = "\";\n";
    public static final String DOUBLE_QUOTE_DOT_DOUBLE_QUOTE = "\".\"";
    public static final String BACK_QUOTE_DOT_BACK_QUOTE = "`.`";
    public static final String OPEN_SQUARE_BRACKET_DOT_OPEN_SQUARE_BRACKET = "].[";
    public static final String EMPTY_PARAMETER_LIST = "()";

    public static final String DEFAULT_STATEMENT_DELIMITER = SEMICOLON;

    public static final String SQL_AND = " AND ";
    public static final String SQL_AND_LOWER = " and ";
    public static final String SQL_AS_KEYWORD = "AS ";
    public static final String LINE_SEPARATOR_SQL_AS = LINE_SEPARATOR + SQL_AS_KEYWORD;
    public static final String SQL_WITH = "WITH ";
    public static final String LINE_SEPARATOR_SQL_WITH = LINE_SEPARATOR + SQL_WITH;
    public static final String LINE_SEPARATOR_WITH_CHECK_OPTION = LINE_SEPARATOR + "WITH CHECK OPTION";
    public static final String CREATE_OR_REPLACE_VIEW_SQL_PREFIX = "CREATE OR REPLACE VIEW ";
    public static final String CREATE_OR_REPLACE_FUNCTION_SQL_PREFIX = "CREATE OR REPLACE FUNCTION ";
    public static final String CREATE_OR_REPLACE_PROCEDURE_SQL_PREFIX = "CREATE OR REPLACE PROCEDURE ";
    public static final String CREATE_OR_REPLACE_TRIGGER_SQL_PREFIX = "CREATE OR REPLACE TRIGGER ";
    public static final String SQL_AS = " AS ";
    public static final String SQL_AS_LINE_SEPARATOR = " AS " + LINE_SEPARATOR;
    public static final String SQL_ON = " ON ";
    public static final String SQL_TO = " TO ";
    public static final String SQL_IS = " IS ";
    public static final String SQL_IS_LOWER = " is ";
    public static final String SQL_IS_SINGLE_QUOTE = " IS '";
    public static final String SQL_IS_NULL = " IS NULL";
    public static final String SQL_LIKE = " LIKE ";
    public static final String SQL_IN_OPEN_PARENTHESIS = " IN (";
    public static final String SQL_OR = " OR ";
    public static final String SQL_OR_REPLACE = "OR REPLACE ";
    public static final String CHECK_OPTION_SQL = " CHECK OPTION ";
    public static final String SELECT_SQL_PREFIX = "SELECT ";
    public static final String SELECT_ALL_FROM_SQL_PREFIX = "SELECT * FROM ";
    public static final String INSERT_INTO_SQL_PREFIX = "INSERT INTO ";
    public static final String UPDATE_SQL_PREFIX = "UPDATE ";
    public static final String DELETE_FROM_SQL_PREFIX = "DELETE FROM ";
    public static final String VALUES_SQL = " VALUES ";
    public static final String SET_SQL = " SET ";
    public static final String SET_SQL_LOWER = " set ";
    public static final String WHERE_SQL = " WHERE ";
    public static final String WHERE_SQL_PREFIX = "WHERE ";
    public static final String WHERE_SQL_LOWER = " where ";
    public static final String WHERE_KEYWORD = "WHERE";
    public static final String FROM_SQL_PREFIX = " FROM ";
    public static final String ORDER_BY_SQL_PREFIX = " ORDER BY ";
    public static final String ALL_COLUMNS = "*";
    public static final String GREATER_THAN_SQL = " > ";
    public static final String LESS_THAN_SQL = " < ";
    public static final String ASCENDING_SQL = " ASC";
    public static final String DESCENDING_SQL = " DESC";
    public static final String FROM_WHERE_SQL = " FROM where";
    public static final String EQUAL_SQL = " = ";
    public static final String NULL_SQL = " NULL";
    public static final String NOT_NULL_SQL_WITH_PREFIX = " NOT NULL";
    public static final String LINE_SEPARATOR_LIMIT_SQL = "\n LIMIT ";
    public static final String LIMIT_SQL = " LIMIT ";
    public static final String LINE_SEPARATOR_OFFSET_SQL = "\n OFFSET ";
    public static final String OFFSET_SQL = " OFFSET ";
    public static final String FETCH_NEXT_SQL = " FETCH NEXT ";
    public static final String ROWS_SQL = " ROWS ";
    public static final String ROWS_ONLY_SQL = " ROWS ONLY";
    public static final String EXPLAIN_SQL_PREFIX = "EXPLAIN ";
    public static final String DROP_TABLE_SQL_PREFIX = "DROP TABLE ";
    public static final String DROP_FUNCTION_SQL_PREFIX = "DROP FUNCTION ";
    public static final String DROP_TRIGGER_SQL_PREFIX = "DROP TRIGGER ";
    public static final String DROP_PROCEDURE_SQL_PREFIX = "DROP PROCEDURE ";
    public static final String DROP_VIEW_SQL_PREFIX = "DROP VIEW ";
    public static final String DROP_TABLE_IF_EXISTS_SQL_PREFIX = "DROP TABLE IF EXISTS ";
    public static final String DROP_FUNCTION_IF_EXISTS_SQL_PREFIX = "DROP FUNCTION IF EXISTS ";
    public static final String DROP_PROCEDURE_IF_EXISTS_SQL_PREFIX = "DROP PROCEDURE IF EXISTS ";
    public static final String DROP_TRIGGER_IF_EXISTS_SQL_PREFIX = "DROP TRIGGER IF EXISTS ";
    public static final String DROP_VIEW_IF_EXISTS_SQL_PREFIX = "DROP VIEW IF EXISTS ";
    public static final String DROP_DATABASE_SQL_PREFIX = "DROP DATABASE ";
    public static final String CREATE_DATABASE_SQL_PREFIX = "CREATE DATABASE ";
    public static final String USE_DATABASE_SQL_PREFIX = "USE ";
    public static final String TRUNCATE_TABLE_SQL_PREFIX = "TRUNCATE TABLE ";
    public static final String CREATE_TABLE_SQL_PREFIX = "CREATE TABLE ";
    public static final String ALTER_TABLE_SQL_PREFIX = "ALTER TABLE ";
    public static final String CREATE_SCHEMA_SQL_PREFIX = "CREATE SCHEMA ";
    public static final String CREATE_SQL_PREFIX = "CREATE ";
    public static final String CREATE_KEYWORD = "CREATE";
    public static final String UPDATE_KEYWORD = "UPDATE";
    public static final String DELETE_KEYWORD = "DELETE";
    public static final String CREATE_INDEX_SQL_PREFIX = "CREATE INDEX ";
    public static final String CREATE_UNIQUE_INDEX_SQL_PREFIX = "CREATE UNIQUE INDEX ";
    public static final String UNIQUE_SQL = "UNIQUE ";
    public static final String INDEX_SQL = "INDEX ";
    public static final String IF_NOT_EXISTS_SQL = "IF NOT EXISTS ";
    public static final String FORCE_SQL = "FORCE ";
    public static final String CREATE_TABLE_AS_SELECT_FROM_SQL = " AS SELECT * FROM ";
    public static final String EMPTY_RESULT_WHERE_SQL = " WHERE 1=0";
    public static final String TABLE_RENAME_SQL = " RENAME TO ";
    public static final String COLUMN_RENAME_SQL = " RENAME COLUMN ";
    public static final String COLUMN_ADD_SQL = " ADD " + OPEN_PARENTHESIS;
    public static final String COLUMN_DROP_SQL = " DROP COLUMN ";
    public static final String COLUMN_MODIFY_SQL = " MODIFY " + OPEN_PARENTHESIS;
    public static final String CONSTRAINT_ADD_SQL = " ADD CONSTRAINT ";
    public static final String PRIMARY_KEY_SQL = " PRIMARY KEY ";
    public static final String DROP_PRIMARY_KEY_SQL = " DROP PRIMARY KEY";
    public static final String DROP_INDEX_SQL_PREFIX = "DROP INDEX ";
    public static final String NOT_NULL_SQL = "NOT NULL";
    public static final String SQL_IS_NULL_LOWER_AND = " is null and ";
    public static final String ENGINE_SQL = " ENGINE=";
    public static final String DEFAULT_CHARACTER_SET_SQL = " DEFAULT CHARACTER SET=";
    public static final String COLLATE_SQL = " COLLATE=";
    public static final String AUTO_INCREMENT_SQL = " AUTO_INCREMENT=";
    public static final String DEFAULT_SQL_PREFIX = "DEFAULT ";
    public static final String DEFAULT_SQL = "DEFAULT";
    public static final String DEFAULT_SQL_WITH_COMMA = "DEFAULT,";
    public static final String DEFAULT_EMPTY_STRING_SQL = "DEFAULT ''";
    public static final String DEFAULT_NULL_SQL = "DEFAULT NULL";
    public static final String COMMENT_ON_TABLE_SQL_PREFIX = "COMMENT ON TABLE ";
    public static final String COMMENT_ON_COLUMN_SQL_PREFIX = "COMMENT ON COLUMN ";
    public static final String COLUMN_COMMENT_SQL_PREFIX = " comment '";
    public static final String CREATE_VIEW_KEYWORD = "VIEW ";
    public static final String VIEW_KEYWORD = "VIEW ";
    public static final String SCHEMA_AUTHORIZATION_SQL = " AUTHORIZATION ";
    public static final String TRIGGER_EACH_ROW = "EACH ROW";
    public static final String TRIGGER_FOR_EACH_ROW_SQL = "FOR EACH ROW ";

    private SQLConstants() {
    }
}
